export const homeObjOne = {
  align: true,
  lightBg: false,
  primary: true,
  imgStart: '',
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: '로그인',
  description: `리액트로 만든 영화정보 사이트입니다.\nmysql,express를 이용하여 기본적인 CRUD를 개발하였으며,\n unDraw, youtube를 참고하여 페이지를 제작하게 되었습니다.
    영화 후기를 등록하여 다른사람과 생각을 공유할 수 있고, 
    다른 영화 정보들을 참고하실 수 있는 웹사이트입니다.`,
  headline: `방문해주신 이용자분들께\n감사의 말씀을 드립니다.`,
  lightText: true,
  topLine: `making for react`,
  img: require('../../images/Hello.svg').default,
  alt: 'Image',
  start: '',
};

export const homeObjTwo = {
  align: false,
  lightBg: true,
  primary: false,
  imgStart: 'start',
  lightTopLine: false,
  lightTextDesc: false,
  buttonLabel: '자세히보기',
  description: `자신이 보았던 영화를 간략하게 소개하며 내가 보지 못한 영화를 빠르게 파악할 수 있습니다.`,
  headline: `모든 영화를 한 눈에 파악하자`,
  lightText: false,
  topLine: `Movies`,
  img: require('../../images/home_cinema.svg').default,
  alt: 'Image',
  start: 'true',
};

export const homeObjThree = {
  align: true,
  lightBg: false,
  primary: true,
  imgStart: '',
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: '자세히보기',
  description: `저희 사이트에 대한 피드백, 하고싶은 말, 아무거나 흔적을 남겨주세요. 큰 힘이 됩니다.`,
  headline: `자유 게시판을 이용하여 \n방문 흔적을 남겨주세요`,
  lightText: true,
  topLine: `FreeBoard`,
  img: require('../../images/home_cinema.svg').default,
  alt: 'Image',
  start: '',
};

export const homeObjFour = {
  align: false,
  lightBg: true,
  primary: false,
  imgStart: 'start',
  lightTopLine: false,
  lightTextDesc: false,
  buttonLabel: '자세히보기',
  description: `추가로 궁금한 점이나 개인적으로 요청할게 있으시면 연락주세요.`,
  headline: `저와 연락을 원하시나요?`,
  lightText: false,
  topLine: `Contact`,
  img: require('../../images/home_cinema.svg').default,
  alt: 'Image',
  start: 'true',
};
